; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -verify-machineinstrs -mtriple=arm64-linux \
; RUN:   -O2 -o - < %s 2>&1 | FileCheck %s --check-prefixes=CHECK-64
; RUN: llc -verify-machineinstrs -mtriple=armv7-linux \
; RUN:   -O2 -o - < %s 2>&1 | FileCheck %s --check-prefix=CHECK-32

%union.tu_c = type { i8 }
%union.tu_s = type { i16 }
%union.tu_us = type { i16 }
%union.tu_l = type { i64 }
%union.etest = type { i8 }

define void @ftest0(i8 noundef zeroext %uc.coerce) {
; CHECK-64-LABEL: ftest0:
; CHECK-64:       // %bb.0: // %entry
; CHECK-64-NEXT:    sub sp, sp, #16
; CHECK-64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-64-NEXT:    strb w0, [sp, #15]
; CHECK-64-NEXT:    add sp, sp, #16
; CHECK-64-NEXT:    ret
;
; CHECK-32-LABEL: ftest0:
; CHECK-32:       @ %bb.0: @ %entry
; CHECK-32-NEXT:    sub sp, sp, #4
; CHECK-32-NEXT:    strb r0, [sp, #3]
; CHECK-32-NEXT:    add sp, sp, #4
; CHECK-32-NEXT:    bx lr
entry:
  %uc = alloca %union.tu_c, align 1
  %coerce.dive = getelementptr inbounds %union.tu_c, ptr %uc, i32 0, i32 0
  store i8 %uc.coerce, ptr %coerce.dive, align 1
  ret void
}

define void @ftest1(i16 noundef signext %uc.coerce) {
; CHECK-64-LABEL: ftest1:
; CHECK-64:       // %bb.0: // %entry
; CHECK-64-NEXT:    sub sp, sp, #16
; CHECK-64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-64-NEXT:    strh w0, [sp, #14]
; CHECK-64-NEXT:    add sp, sp, #16
; CHECK-64-NEXT:    ret
;
; CHECK-32-LABEL: ftest1:
; CHECK-32:       @ %bb.0: @ %entry
; CHECK-32-NEXT:    sub sp, sp, #4
; CHECK-32-NEXT:    strh r0, [sp, #2]
; CHECK-32-NEXT:    add sp, sp, #4
; CHECK-32-NEXT:    bx lr
entry:
  %uc = alloca %union.tu_s, align 2
  %coerce.dive = getelementptr inbounds %union.tu_s, ptr %uc, i32 0, i32 0
  store i16 %uc.coerce, ptr %coerce.dive, align 2
  ret void
}

define void @ftest2(i16 noundef zeroext %uc.coerce) {
; CHECK-64-LABEL: ftest2:
; CHECK-64:       // %bb.0: // %entry
; CHECK-64-NEXT:    sub sp, sp, #16
; CHECK-64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-64-NEXT:    strh w0, [sp, #14]
; CHECK-64-NEXT:    add sp, sp, #16
; CHECK-64-NEXT:    ret
;
; CHECK-32-LABEL: ftest2:
; CHECK-32:       @ %bb.0: @ %entry
; CHECK-32-NEXT:    sub sp, sp, #4
; CHECK-32-NEXT:    strh r0, [sp, #2]
; CHECK-32-NEXT:    add sp, sp, #4
; CHECK-32-NEXT:    bx lr
entry:
  %uc = alloca %union.tu_us, align 2
  %coerce.dive = getelementptr inbounds %union.tu_us, ptr %uc, i32 0, i32 0
  store i16 %uc.coerce, ptr %coerce.dive, align 2
  ret void
}

define void @ftest3(i64 %uc.coerce) {
; CHECK-64-LABEL: ftest3:
; CHECK-64:       // %bb.0: // %entry
; CHECK-64-NEXT:    sub sp, sp, #16
; CHECK-64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-64-NEXT:    str x0, [sp, #8]
; CHECK-64-NEXT:    add sp, sp, #16
; CHECK-64-NEXT:    ret
;
; CHECK-32-LABEL: ftest3:
; CHECK-32:       @ %bb.0: @ %entry
; CHECK-32-NEXT:    sub sp, sp, #8
; CHECK-32-NEXT:    stm sp!, {r0, r1}
; CHECK-32-NEXT:    bx lr
entry:
  %uc = alloca %union.tu_l, align 8
  %coerce.dive = getelementptr inbounds %union.tu_l, ptr %uc, i32 0, i32 0
  store i64 %uc.coerce, ptr %coerce.dive, align 8
  ret void
}

define dso_local void @ftest4(i8 noundef zeroext %a.coerce) #0 {
; CHECK-64-LABEL: ftest4:
; CHECK-64:       // %bb.0: // %entry
; CHECK-64-NEXT:    sub sp, sp, #16
; CHECK-64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-64-NEXT:    strb w0, [sp, #15]
; CHECK-64-NEXT:    add sp, sp, #16
; CHECK-64-NEXT:    ret
;
; CHECK-32-LABEL: ftest4:
; CHECK-32:       @ %bb.0: @ %entry
; CHECK-32-NEXT:    sub sp, sp, #4
; CHECK-32-NEXT:    strb r0, [sp, #3]
; CHECK-32-NEXT:    add sp, sp, #4
; CHECK-32-NEXT:    bx lr
entry:
  %a = alloca %union.etest, align 1
  %coerce.dive = getelementptr inbounds %union.etest, ptr %a, i32 0, i32 0
  store i8 %a.coerce, ptr %coerce.dive, align 1
  ret void
}
