// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: powerpc-registered-target
// RUN: %clang_cc1 -triple powerpc64-unknown-linux-gnu -target-feature +altivec \
// RUN:   -target-feature +future-vector -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -triple powerpc64le-unknown-linux-gnu -target-feature +altivec \
// RUN:   -target-feature +future-vector -emit-llvm %s -o - | FileCheck %s

#include <altivec.h>

// CHECK-LABEL: @test_vec_uncompressh(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[__A_ADDR_I:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[__B_ADDR_I:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    store <16 x i8> [[A:%.*]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[B:%.*]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <16 x i8>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    store <16 x i8> [[TMP0]], ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    store <4 x i32> [[TMP1]], ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <16 x i8>, ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.ppc.altivec.vucmprhn(<16 x i8> [[TMP2]], <4 x i32> [[TMP3]])
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
__attribute__((noinline)) vector signed short test_vec_uncompressh(vector unsigned char a, vector unsigned int b) {
  return vec_uncompressh(a, b);
}

// CHECK-LABEL: @test_builtin_altivec_vucmprhn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    store <16 x i8> [[A:%.*]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[B:%.*]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <16 x i8>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i16> @llvm.ppc.altivec.vucmprhn(<16 x i8> [[TMP0]], <4 x i32> [[TMP1]])
// CHECK-NEXT:    ret <8 x i16> [[TMP2]]
//
__attribute__((noinline)) vector signed short test_builtin_altivec_vucmprhn(vector unsigned char a, vector unsigned int b) {
  return __builtin_altivec_vucmprhn(a, b);
}

// Made with Bob
