// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: powerpc-registered-target
// RUN: %clang_cc1 -triple powerpc64-unknown-linux-gnu -target-cpu future \
// RUN:   -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -triple powerpc64le-unknown-linux-gnu -target-cpu future \
// RUN:   -emit-llvm %s -o - | FileCheck %s

#include <altivec.h>

// CHECK-LABEL: @test_vec_uncompresshn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[__A_ADDR_I:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[__B_ADDR_I:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    store <16 x i8> [[A:%.*]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[B:%.*]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <16 x i8>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    store <16 x i8> [[TMP0]], ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    store <4 x i32> [[TMP1]], ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <16 x i8>, ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.ppc.altivec.vucmprhn(<16 x i8> [[TMP2]], <4 x i32> [[TMP3]])
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
__attribute__((noinline)) vector signed short test_vec_uncompresshn(vector unsigned char a, vector unsigned int b) {
  return vec_uncompresshn(a, b);
}

// CHECK-LABEL: @test_builtin_altivec_vucmprhn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    store <16 x i8> [[A:%.*]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[B:%.*]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <16 x i8>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i16> @llvm.ppc.altivec.vucmprhn(<16 x i8> [[TMP0]], <4 x i32> [[TMP1]])
// CHECK-NEXT:    ret <8 x i16> [[TMP2]]
//
__attribute__((noinline)) vector signed short test_builtin_altivec_vucmprhn(vector unsigned char a, vector unsigned int b) {
  return __builtin_altivec_vucmprhn(a, b);
}

// CHECK-LABEL: @test_vec_uncompresshb(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[__A_ADDR_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[__B_ADDR_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    store <8 x i16> [[A:%.*]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <8 x i16> [[B:%.*]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP0]], ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP1]], ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <8 x i16>, ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i16>, ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = call <4 x i32> @llvm.ppc.altivec.vucmprhb(<8 x i16> [[TMP2]], <8 x i16> [[TMP3]])
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
__attribute__((noinline)) vector signed int test_vec_uncompresshb(vector unsigned short a, vector unsigned short b) {
  return vec_uncompresshb(a, b);
}

// CHECK-LABEL: @test_vec_uncompresshh(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[__A_ADDR_I:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[__B_ADDR_I:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    store <4 x i32> [[A:%.*]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <16 x i8> [[B:%.*]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i32>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i8>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[TMP0]], ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    store <16 x i8> [[TMP1]], ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i8>, ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = call <2 x i64> @llvm.ppc.altivec.vucmprhh(<4 x i32> [[TMP2]], <16 x i8> [[TMP3]])
// CHECK-NEXT:    ret <2 x i64> [[TMP4]]
//
__attribute__((noinline)) vector signed long long test_vec_uncompresshh(vector unsigned int a, vector unsigned char b) {
  return vec_uncompresshh(a, b);
}

// CHECK-LABEL: @test_vec_uncompressln(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[__A_ADDR_I:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[__B_ADDR_I:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    store <16 x i8> [[A:%.*]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[B:%.*]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <16 x i8>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    store <16 x i8> [[TMP0]], ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    store <4 x i32> [[TMP1]], ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <16 x i8>, ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = call <8 x i16> @llvm.ppc.altivec.vucmprln(<16 x i8> [[TMP2]], <4 x i32> [[TMP3]])
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
__attribute__((noinline)) vector signed short test_vec_uncompressln(vector unsigned char a, vector unsigned int b) {
  return vec_uncompressln(a, b);
}

// CHECK-LABEL: @test_vec_uncompresslb(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[__A_ADDR_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[__B_ADDR_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    store <8 x i16> [[A:%.*]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <8 x i16> [[B:%.*]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP0]], ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP1]], ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <8 x i16>, ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i16>, ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = call <4 x i32> @llvm.ppc.altivec.vucmprlb(<8 x i16> [[TMP2]], <8 x i16> [[TMP3]])
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
__attribute__((noinline)) vector signed int test_vec_uncompresslb(vector unsigned short a, vector unsigned short b) {
  return vec_uncompresslb(a, b);
}

// CHECK-LABEL: @test_vec_uncompresslh(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[__A_ADDR_I:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[__B_ADDR_I:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    store <4 x i32> [[A:%.*]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <16 x i8> [[B:%.*]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i32>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i8>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[TMP0]], ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    store <16 x i8> [[TMP1]], ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr [[__A_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i8>, ptr [[__B_ADDR_I]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = call <2 x i64> @llvm.ppc.altivec.vucmprlh(<4 x i32> [[TMP2]], <16 x i8> [[TMP3]])
// CHECK-NEXT:    ret <2 x i64> [[TMP4]]
//
__attribute__((noinline)) vector signed long long test_vec_uncompresslh(vector unsigned int a, vector unsigned char b) {
  return vec_uncompresslh(a, b);
}

// Made with Bob
