// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -O3 -triple powerpc64le-unknown-unknown -target-cpu future \
// RUN:   -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O3 -triple powerpc64-unknown-unknown -target-cpu future \
// RUN:   -emit-llvm %s -o - | FileCheck %s

// CHECK-LABEL: define dso_local void @test_aes_encrypt_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef readonly captures(none) [[VPP2:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <256 x i1>, ptr [[VPP2]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <256 x i1> @llvm.ppc.aes.encrypt.paired(<256 x i1> [[TMP0]], <256 x i1> [[TMP1]], i32 0)
// CHECK-NEXT:    store <256 x i1> [[TMP2]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes_encrypt_paired(unsigned char *vpp1, unsigned char *vpp2, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair vp2 = *((__vector_pair *)vpp2);
  __vector_pair res = __builtin_aes_encrypt_paired(vp1, vp2, 0);
  *((__vector_pair *)resp) = res;
}

// CHECK-LABEL: define dso_local void @test_aes128_encrypt_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef readonly captures(none) [[VPP2:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <256 x i1>, ptr [[VPP2]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <256 x i1> @llvm.ppc.aes.encrypt.paired(<256 x i1> [[TMP0]], <256 x i1> [[TMP1]], i32 0)
// CHECK-NEXT:    store <256 x i1> [[TMP2]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes128_encrypt_paired(unsigned char *vpp1, unsigned char *vpp2, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair vp2 = *((__vector_pair *)vpp2);
  __vector_pair res = __builtin_aes128_encrypt_paired(vp1, vp2);
  *((__vector_pair *)resp) = res;
}

// CHECK-LABEL: define dso_local void @test_aes192_encrypt_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef readonly captures(none) [[VPP2:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <256 x i1>, ptr [[VPP2]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <256 x i1> @llvm.ppc.aes.encrypt.paired(<256 x i1> [[TMP0]], <256 x i1> [[TMP1]], i32 1)
// CHECK-NEXT:    store <256 x i1> [[TMP2]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes192_encrypt_paired(unsigned char *vpp1, unsigned char *vpp2, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair vp2 = *((__vector_pair *)vpp2);
  __vector_pair res = __builtin_aes192_encrypt_paired(vp1, vp2);
  *((__vector_pair *)resp) = res;
}

// CHECK-LABEL: define dso_local void @test_aes256_encrypt_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef readonly captures(none) [[VPP2:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <256 x i1>, ptr [[VPP2]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <256 x i1> @llvm.ppc.aes.encrypt.paired(<256 x i1> [[TMP0]], <256 x i1> [[TMP1]], i32 2)
// CHECK-NEXT:    store <256 x i1> [[TMP2]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes256_encrypt_paired(unsigned char *vpp1, unsigned char *vpp2, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair vp2 = *((__vector_pair *)vpp2);
  __vector_pair res = __builtin_aes256_encrypt_paired(vp1, vp2);
  *((__vector_pair *)resp) = res;
}

// CHECK-LABEL: define dso_local void @test_aes_decrypt_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef readonly captures(none) [[VPP2:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <256 x i1>, ptr [[VPP2]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <256 x i1> @llvm.ppc.aes.decrypt.paired(<256 x i1> [[TMP0]], <256 x i1> [[TMP1]], i32 0)
// CHECK-NEXT:    store <256 x i1> [[TMP2]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes_decrypt_paired(unsigned char *vpp1, unsigned char *vpp2, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair vp2 = *((__vector_pair *)vpp2);
  __vector_pair res = __builtin_aes_decrypt_paired(vp1, vp2, 0);
  *((__vector_pair *)resp) = res;
}

// CHECK-LABEL: define dso_local void @test_aes128_decrypt_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef readonly captures(none) [[VPP2:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <256 x i1>, ptr [[VPP2]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <256 x i1> @llvm.ppc.aes.decrypt.paired(<256 x i1> [[TMP0]], <256 x i1> [[TMP1]], i32 0)
// CHECK-NEXT:    store <256 x i1> [[TMP2]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes128_decrypt_paired(unsigned char *vpp1, unsigned char *vpp2, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair vp2 = *((__vector_pair *)vpp2);
  __vector_pair res = __builtin_aes128_decrypt_paired(vp1, vp2);
  *((__vector_pair *)resp) = res;
}

// CHECK-LABEL: define dso_local void @test_aes192_decrypt_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef readonly captures(none) [[VPP2:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <256 x i1>, ptr [[VPP2]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <256 x i1> @llvm.ppc.aes.decrypt.paired(<256 x i1> [[TMP0]], <256 x i1> [[TMP1]], i32 1)
// CHECK-NEXT:    store <256 x i1> [[TMP2]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes192_decrypt_paired(unsigned char *vpp1, unsigned char *vpp2, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair vp2 = *((__vector_pair *)vpp2);
  __vector_pair res = __builtin_aes192_decrypt_paired(vp1, vp2);
  *((__vector_pair *)resp) = res;
}

// CHECK-LABEL: define dso_local void @test_aes256_decrypt_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef readonly captures(none) [[VPP2:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <256 x i1>, ptr [[VPP2]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <256 x i1> @llvm.ppc.aes.decrypt.paired(<256 x i1> [[TMP0]], <256 x i1> [[TMP1]], i32 2)
// CHECK-NEXT:    store <256 x i1> [[TMP2]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes256_decrypt_paired(unsigned char *vpp1, unsigned char *vpp2, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair vp2 = *((__vector_pair *)vpp2);
  __vector_pair res = __builtin_aes256_decrypt_paired(vp1, vp2);
  *((__vector_pair *)resp) = res;
}
// CHECK-LABEL: define dso_local void @test_aes_genlastkey_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <256 x i1> @llvm.ppc.aes.genlastkey.paired(<256 x i1> [[TMP0]], i32 0)
// CHECK-NEXT:    store <256 x i1> [[TMP1]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes_genlastkey_paired(unsigned char *vpp1, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair res = __builtin_aes_genlastkey_paired(vp1, 0);
  *((__vector_pair *)resp) = res;
}

// CHECK-LABEL: define dso_local void @test_aes128_genlastkey_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <256 x i1> @llvm.ppc.aes.genlastkey.paired(<256 x i1> [[TMP0]], i32 0)
// CHECK-NEXT:    store <256 x i1> [[TMP1]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes128_genlastkey_paired(unsigned char *vpp1, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair res = __builtin_aes128_genlastkey_paired(vp1);
  *((__vector_pair *)resp) = res;
}

// CHECK-LABEL: define dso_local void @test_aes192_genlastkey_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <256 x i1> @llvm.ppc.aes.genlastkey.paired(<256 x i1> [[TMP0]], i32 1)
// CHECK-NEXT:    store <256 x i1> [[TMP1]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes192_genlastkey_paired(unsigned char *vpp1, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair res = __builtin_aes192_genlastkey_paired(vp1);
  *((__vector_pair *)resp) = res;
}

// CHECK-LABEL: define dso_local void @test_aes256_genlastkey_paired(
// CHECK-SAME: ptr noundef readonly captures(none) [[VPP1:%.*]], ptr noundef writeonly captures(none) initializes((0, 32)) [[RESP:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <256 x i1>, ptr [[VPP1]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <256 x i1> @llvm.ppc.aes.genlastkey.paired(<256 x i1> [[TMP0]], i32 2)
// CHECK-NEXT:    store <256 x i1> [[TMP1]], ptr [[RESP]], align 32
// CHECK-NEXT:    ret void
//
void test_aes256_genlastkey_paired(unsigned char *vpp1, unsigned char *resp) {
  __vector_pair vp1 = *((__vector_pair *)vpp1);
  __vector_pair res = __builtin_aes256_genlastkey_paired(vp1);
  *((__vector_pair *)resp) = res;
}



// Made with AI
