; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -verify-machineinstrs -mtriple=riscv64-unknown-linux \
; RUN:   -O2 -o - < %s 2>&1 | FileCheck %s --check-prefixes=CHECK,CHECK-64
; RUN: llc -verify-machineinstrs -mtriple=riscv32-unknown-linux \
; RUN:   -O2 -o - < %s 2>&1 | FileCheck %s --check-prefixes=CHECK,CHECK-32

%union.tu_c = type { i8 }
%union.tu_s = type { i16 }
%union.tu_us = type { i16 }
%union.tu_l = type { i64 }
%union.etest = type { i8 }

define void @ftest0(i8 noundef zeroext %uc.coerce) {
; CHECK-LABEL: ftest0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sb a0, 15(sp)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  %uc = alloca %union.tu_c, align 1
  %coerce.dive = getelementptr inbounds %union.tu_c, ptr %uc, i32 0, i32 0
  store i8 %uc.coerce, ptr %coerce.dive, align 1
  ret void
}

define void @ftest1(i16 noundef signext %uc.coerce) {
; CHECK-LABEL: ftest1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sh a0, 14(sp)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  %uc = alloca %union.tu_s, align 2
  %coerce.dive = getelementptr inbounds %union.tu_s, ptr %uc, i32 0, i32 0
  store i16 %uc.coerce, ptr %coerce.dive, align 2
  ret void
}

define void @ftest2(i16 noundef zeroext %uc.coerce) {
; CHECK-LABEL: ftest2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sh a0, 14(sp)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  %uc = alloca %union.tu_us, align 2
  %coerce.dive = getelementptr inbounds %union.tu_us, ptr %uc, i32 0, i32 0
  store i16 %uc.coerce, ptr %coerce.dive, align 2
  ret void
}

define void @ftest3(i64 %uc.coerce) {
; CHECK-64-LABEL: ftest3:
; CHECK-64:       # %bb.0: # %entry
; CHECK-64-NEXT:    addi sp, sp, -16
; CHECK-64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-64-NEXT:    sd a0, 8(sp)
; CHECK-64-NEXT:    addi sp, sp, 16
; CHECK-64-NEXT:    ret
;
; CHECK-32-LABEL: ftest3:
; CHECK-32:       # %bb.0: # %entry
; CHECK-32-NEXT:    addi sp, sp, -16
; CHECK-32-NEXT:    .cfi_def_cfa_offset 16
; CHECK-32-NEXT:    sw a1, 12(sp)
; CHECK-32-NEXT:    sw a0, 8(sp)
; CHECK-32-NEXT:    addi sp, sp, 16
; CHECK-32-NEXT:    ret
entry:
  %uc = alloca %union.tu_l, align 8
  %coerce.dive = getelementptr inbounds %union.tu_l, ptr %uc, i32 0, i32 0
  store i64 %uc.coerce, ptr %coerce.dive, align 8
  ret void
}

define dso_local void @ftest4(i8 noundef zeroext %a.coerce) #0 {
; CHECK-LABEL: ftest4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sb a0, 15(sp)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  %a = alloca %union.etest, align 1
  %coerce.dive = getelementptr inbounds %union.etest, ptr %a, i32 0, i32 0
  store i8 %a.coerce, ptr %coerce.dive, align 1
  ret void
}
