; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -verify-machineinstrs -mtriple=aarch64 -O2 -o - < %s 2>&1 \
; RUN:   | FileCheck %s

%union.tu_c = type { i8 }
%union.tu_s = type { i16 }
%union.tu_us = type { i16 }
%union.tu_l = type { i64 }
%union.etest = type { i8 }

define void @ftest0(i8 noundef zeroext %uc.coerce) {
; CHECK-LABEL: ftest0:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub sp, sp, #16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    strb w0, [sp, #15]
; CHECK-NEXT:    add sp, sp, #16
; CHECK-NEXT:    ret
entry:
  %uc = alloca %union.tu_c, align 1
  %coerce.dive = getelementptr inbounds %union.tu_c, ptr %uc, i32 0, i32 0
  store i8 %uc.coerce, ptr %coerce.dive, align 1
  ret void
}

define void @ftest1(i16 noundef signext %uc.coerce) {
; CHECK-LABEL: ftest1:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub sp, sp, #16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    strh w0, [sp, #14]
; CHECK-NEXT:    add sp, sp, #16
; CHECK-NEXT:    ret
entry:
  %uc = alloca %union.tu_s, align 2
  %coerce.dive = getelementptr inbounds %union.tu_s, ptr %uc, i32 0, i32 0
  store i16 %uc.coerce, ptr %coerce.dive, align 2
  ret void
}

define void @ftest2(i16 noundef zeroext %uc.coerce) {
; CHECK-LABEL: ftest2:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub sp, sp, #16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    strh w0, [sp, #14]
; CHECK-NEXT:    add sp, sp, #16
; CHECK-NEXT:    ret
entry:
  %uc = alloca %union.tu_us, align 2
  %coerce.dive = getelementptr inbounds %union.tu_us, ptr %uc, i32 0, i32 0
  store i16 %uc.coerce, ptr %coerce.dive, align 2
  ret void
}

define void @ftest3(i64 %uc.coerce) {
; CHECK-LABEL: ftest3:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub sp, sp, #16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    str x0, [sp, #8]
; CHECK-NEXT:    add sp, sp, #16
; CHECK-NEXT:    ret
entry:
  %uc = alloca %union.tu_l, align 8
  %coerce.dive = getelementptr inbounds %union.tu_l, ptr %uc, i32 0, i32 0
  store i64 %uc.coerce, ptr %coerce.dive, align 8
  ret void
}

define dso_local void @ftest4(i8 noundef zeroext %a.coerce) #0 {
; CHECK-LABEL: ftest4:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub sp, sp, #16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    strb w0, [sp, #15]
; CHECK-NEXT:    add sp, sp, #16
; CHECK-NEXT:    ret
entry:
  %a = alloca %union.etest, align 1
  %coerce.dive = getelementptr inbounds %union.etest, ptr %a, i32 0, i32 0
  store i8 %a.coerce, ptr %coerce.dive, align 1
  ret void
}
