; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -mtriple=powerpc64le-unknown-linux-gnu \
; RUN:   -mcpu=future < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-unknown-linux-gnu \
; RUN:   -mcpu=future < %s | FileCheck %s

declare <8 x i16> @llvm.ppc.altivec.vucmprhn(<16 x i8>, <4 x i32>)

define <8 x i16> @test_vucmprhn(<16 x i8> %a, <4 x i32> %b) {
; CHECK-LABEL: test_vucmprhn:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vucmprhn 2, 2, 3
; CHECK-NEXT:    blr
entry:
  %0 = tail call <8 x i16> @llvm.ppc.altivec.vucmprhn(<16 x i8> %a, <4 x i32> %b)
  ret <8 x i16> %0
}