; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -mtriple=powerpc64le-unknown-linux-gnu \
; RUN:   -mcpu=future -ppc-asm-full-reg-names -ppc-vsr-nums-as-vr \
; RUN:   < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -mtriple=powerpc64-unknown-linux-gnu \
; RUN:   -mcpu=future -ppc-asm-full-reg-names -ppc-vsr-nums-as-vr \
; RUN:   < %s | FileCheck %s --check-prefix=CHECK-BE

; Generated by AI.

declare <256 x i1> @llvm.ppc.aes.encrypt.paired(<256 x i1>, <256 x i1>, i32)

define void @test_aes_encrypt_paired_imm0(ptr %ptr, ptr %vpp1, ptr %vpp2) {
; CHECK-LABEL: test_aes_encrypt_paired_imm0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lxvp vsp{{[0-9]+}}, 0(r4)
; CHECK-NEXT:    lxvp vsp{{[0-9]+}}, 0(r5)
; CHECK-NEXT:    xxaes128encp vsp{{[0-9]+}}, vsp{{[0-9]+}}, vsp{{[0-9]+}}
; CHECK-NEXT:    stxvp vsp{{[0-9]+}}, 0(r3)
; CHECK-NEXT:    blr
;
; CHECK-BE-LABEL: test_aes_encrypt_paired_imm0:
; CHECK-BE:       # %bb.0: # %entry
; CHECK-BE-NEXT:    lxvp vsp{{[0-9]+}}, 0(r4)
; CHECK-BE-NEXT:    lxvp vsp{{[0-9]+}}, 0(r5)
; CHECK-BE-NEXT:    xxaes128encp vsp{{[0-9]+}}, vsp{{[0-9]+}}, vsp{{[0-9]+}}
; CHECK-BE-NEXT:    stxvp vsp{{[0-9]+}}, 0(r3)
; CHECK-BE-NEXT:    blr
entry:
  %vp1 = load <256 x i1>, ptr %vpp1, align 32
  %vp2 = load <256 x i1>, ptr %vpp2, align 32
  %0 = tail call <256 x i1> @llvm.ppc.aes.encrypt.paired(<256 x i1> %vp1, <256 x i1> %vp2, i32 0)
  store <256 x i1> %0, ptr %ptr, align 32
  ret void
}

define void @test_aes_encrypt_paired_imm1(ptr %ptr, ptr %vpp1, ptr %vpp2) {
; CHECK-LABEL: test_aes_encrypt_paired_imm1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lxvp vsp{{[0-9]+}}, 0(r4)
; CHECK-NEXT:    lxvp vsp{{[0-9]+}}, 0(r5)
; CHECK-NEXT:    xxaes192encp vsp{{[0-9]+}}, vsp{{[0-9]+}}, vsp{{[0-9]+}}
; CHECK-NEXT:    stxvp vsp{{[0-9]+}}, 0(r3)
; CHECK-NEXT:    blr
;
; CHECK-BE-LABEL: test_aes_encrypt_paired_imm1:
; CHECK-BE:       # %bb.0: # %entry
; CHECK-BE-NEXT:    lxvp vsp{{[0-9]+}}, 0(r4)
; CHECK-BE-NEXT:    lxvp vsp{{[0-9]+}}, 0(r5)
; CHECK-BE-NEXT:    xxaes192encp vsp{{[0-9]+}}, vsp{{[0-9]+}}, vsp{{[0-9]+}}
; CHECK-BE-NEXT:    stxvp vsp{{[0-9]+}}, 0(r3)
; CHECK-BE-NEXT:    blr
entry:
  %vp1 = load <256 x i1>, ptr %vpp1, align 32
  %vp2 = load <256 x i1>, ptr %vpp2, align 32
  %0 = tail call <256 x i1> @llvm.ppc.aes.encrypt.paired(<256 x i1> %vp1, <256 x i1> %vp2, i32 1)
  store <256 x i1> %0, ptr %ptr, align 32
  ret void
}

define void @test_aes_encrypt_paired_imm2(ptr %ptr, ptr %vpp1, ptr %vpp2) {
; CHECK-LABEL: test_aes_encrypt_paired_imm2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lxvp vsp{{[0-9]+}}, 0(r4)
; CHECK-NEXT:    lxvp vsp{{[0-9]+}}, 0(r5)
; CHECK-NEXT:    xxaes256encp vsp{{[0-9]+}}, vsp{{[0-9]+}}, vsp{{[0-9]+}}
; CHECK-NEXT:    stxvp vsp{{[0-9]+}}, 0(r3)
; CHECK-NEXT:    blr
;
; CHECK-BE-LABEL: test_aes_encrypt_paired_imm2:
; CHECK-BE:       # %bb.0: # %entry
; CHECK-BE-NEXT:    lxvp vsp{{[0-9]+}}, 0(r4)
; CHECK-BE-NEXT:    lxvp vsp{{[0-9]+}}, 0(r5)
; CHECK-BE-NEXT:    xxaes256encp vsp{{[0-9]+}}, vsp{{[0-9]+}}, vsp{{[0-9]+}}
; CHECK-BE-NEXT:    stxvp vsp{{[0-9]+}}, 0(r3)
; CHECK-BE-NEXT:    blr
entry:
  %vp1 = load <256 x i1>, ptr %vpp1, align 32
  %vp2 = load <256 x i1>, ptr %vpp2, align 32
  %0 = tail call <256 x i1> @llvm.ppc.aes.encrypt.paired(<256 x i1> %vp1, <256 x i1> %vp2, i32 2)
  store <256 x i1> %0, ptr %ptr, align 32
  ret void
}
