; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs < %s -mtriple=powerpc64-unknown-linux \
; RUN:   -mcpu=pwr8 -ppc-asm-full-reg-names -ppc-vsr-nums-as-vr | FileCheck \
; RUN:   --check-prefix=P8 %s
; RUN: llc -verify-machineinstrs < %s -mtriple=powerpc64le-unknown-linux \
; RUN:   -mcpu=pwr9 -ppc-asm-full-reg-names -ppc-vsr-nums-as-vr | FileCheck \
; RUN:   --check-prefix=P9 %s

; Test STRICT_FNEARBYINT with different rounding modes to ensure:
; 1. Static rounding modes use appropriate instructions that don't raise FE_INEXACT
; 2. Dynamic rounding mode falls back to libcall
; 3. This fixes the bug where nearbyintl() incorrectly raised FE_INEXACT

declare float @llvm.experimental.constrained.nearbyint.f32(float, metadata, metadata)
declare double @llvm.experimental.constrained.nearbyint.f64(double, metadata, metadata)
declare fp128 @llvm.experimental.constrained.nearbyint.f128(fp128, metadata, metadata)

; Test f32 with round.towardzero (should use xsrdpiz)
define float @nearbyint_f32_towardzero(float %f) strictfp nounwind {
; P8-LABEL: nearbyint_f32_towardzero:
; P8:       # %bb.0:
; P8-NEXT:    xsrdpiz f1, f1
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f32_towardzero:
; P9:       # %bb.0:
; P9-NEXT:    xsrdpiz f1, f1
; P9-NEXT:    blr
  %res = call float @llvm.experimental.constrained.nearbyint.f32(
                      float %f,
                      metadata !"round.towardzero",
                      metadata !"fpexcept.strict")
  ret float %res
}

; Test f64 with round.towardzero (should use xsrdpiz)
define double @nearbyint_f64_towardzero(double %d) strictfp nounwind {
; P8-LABEL: nearbyint_f64_towardzero:
; P8:       # %bb.0:
; P8-NEXT:    xsrdpiz f1, f1
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f64_towardzero:
; P9:       # %bb.0:
; P9-NEXT:    xsrdpiz f1, f1
; P9-NEXT:    blr
  %res = call double @llvm.experimental.constrained.nearbyint.f64(
                      double %d,
                      metadata !"round.towardzero",
                      metadata !"fpexcept.strict")
  ret double %res
}

; Test f32 with round.upward (should use xsrdpip)
define float @nearbyint_f32_upward(float %f) strictfp nounwind {
; P8-LABEL: nearbyint_f32_upward:
; P8:       # %bb.0:
; P8-NEXT:    xsrdpip f1, f1
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f32_upward:
; P9:       # %bb.0:
; P9-NEXT:    xsrdpip f1, f1
; P9-NEXT:    blr
  %res = call float @llvm.experimental.constrained.nearbyint.f32(
                      float %f,
                      metadata !"round.upward",
                      metadata !"fpexcept.strict")
  ret float %res
}

; Test f64 with round.upward (should use xsrdpip)
define double @nearbyint_f64_upward(double %d) strictfp nounwind {
; P8-LABEL: nearbyint_f64_upward:
; P8:       # %bb.0:
; P8-NEXT:    xsrdpip f1, f1
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f64_upward:
; P9:       # %bb.0:
; P9-NEXT:    xsrdpip f1, f1
; P9-NEXT:    blr
  %res = call double @llvm.experimental.constrained.nearbyint.f64(
                      double %d,
                      metadata !"round.upward",
                      metadata !"fpexcept.strict")
  ret double %res
}

; Test f32 with round.downward (should use xsrdpim)
define float @nearbyint_f32_downward(float %f) strictfp nounwind {
; P8-LABEL: nearbyint_f32_downward:
; P8:       # %bb.0:
; P8-NEXT:    xsrdpim f1, f1
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f32_downward:
; P9:       # %bb.0:
; P9-NEXT:    xsrdpim f1, f1
; P9-NEXT:    blr
  %res = call float @llvm.experimental.constrained.nearbyint.f32(
                      float %f,
                      metadata !"round.downward",
                      metadata !"fpexcept.strict")
  ret float %res
}

; Test f64 with round.downward (should use xsrdpim)
define double @nearbyint_f64_downward(double %d) strictfp nounwind {
; P8-LABEL: nearbyint_f64_downward:
; P8:       # %bb.0:
; P8-NEXT:    xsrdpim f1, f1
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f64_downward:
; P9:       # %bb.0:
; P9-NEXT:    xsrdpim f1, f1
; P9-NEXT:    blr
  %res = call double @llvm.experimental.constrained.nearbyint.f64(
                      double %d,
                      metadata !"round.downward",
                      metadata !"fpexcept.strict")
  ret double %res
}

; Test f32 with round.tonearest (should use xsrdpi)
define float @nearbyint_f32_tonearest(float %f) strictfp nounwind {
; P8-LABEL: nearbyint_f32_tonearest:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    stdu r1, -112(r1)
; P8-NEXT:    li r4, 1
; P8-NEXT:    std r0, 128(r1)
; P8-NEXT:    bl nearbyintf
; P8-NEXT:    nop
; P8-NEXT:    addi r1, r1, 112
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f32_tonearest:
; P9:       # %bb.0:
; P9-NEXT:    mflr r0
; P9-NEXT:    stdu r1, -32(r1)
; P9-NEXT:    li r4, 1
; P9-NEXT:    std r0, 48(r1)
; P9-NEXT:    bl nearbyintf
; P9-NEXT:    nop
; P9-NEXT:    addi r1, r1, 32
; P9-NEXT:    ld r0, 16(r1)
; P9-NEXT:    mtlr r0
; P9-NEXT:    blr
  %res = call float @llvm.experimental.constrained.nearbyint.f32(
                      float %f,
                      metadata !"round.tonearest",
                      metadata !"fpexcept.strict")
  ret float %res
}

; Test f64 with round.tonearest (should use xsrdpi)
define double @nearbyint_f64_tonearest(double %d) strictfp nounwind {
; P8-LABEL: nearbyint_f64_tonearest:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    stdu r1, -112(r1)
; P8-NEXT:    li r4, 1
; P8-NEXT:    std r0, 128(r1)
; P8-NEXT:    bl nearbyint
; P8-NEXT:    nop
; P8-NEXT:    addi r1, r1, 112
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f64_tonearest:
; P9:       # %bb.0:
; P9-NEXT:    mflr r0
; P9-NEXT:    stdu r1, -32(r1)
; P9-NEXT:    li r4, 1
; P9-NEXT:    std r0, 48(r1)
; P9-NEXT:    bl nearbyint
; P9-NEXT:    nop
; P9-NEXT:    addi r1, r1, 32
; P9-NEXT:    ld r0, 16(r1)
; P9-NEXT:    mtlr r0
; P9-NEXT:    blr
  %res = call double @llvm.experimental.constrained.nearbyint.f64(
                      double %d,
                      metadata !"round.tonearest",
                      metadata !"fpexcept.strict")
  ret double %res
}

; Test f32 with round.tonearestaway (should use libcall - not supported by hardware)
define float @nearbyint_f32_tonearestaway(float %f) strictfp nounwind {
; P8-LABEL: nearbyint_f32_tonearestaway:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    stdu r1, -112(r1)
; P8-NEXT:    li r4, 4
; P8-NEXT:    std r0, 128(r1)
; P8-NEXT:    bl nearbyintf
; P8-NEXT:    nop
; P8-NEXT:    addi r1, r1, 112
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f32_tonearestaway:
; P9:       # %bb.0:
; P9-NEXT:    mflr r0
; P9-NEXT:    stdu r1, -32(r1)
; P9-NEXT:    li r4, 4
; P9-NEXT:    std r0, 48(r1)
; P9-NEXT:    bl nearbyintf
; P9-NEXT:    nop
; P9-NEXT:    addi r1, r1, 32
; P9-NEXT:    ld r0, 16(r1)
; P9-NEXT:    mtlr r0
; P9-NEXT:    blr
  %res = call float @llvm.experimental.constrained.nearbyint.f32(
                      float %f,
                      metadata !"round.tonearestaway",
                      metadata !"fpexcept.strict")
  ret float %res
}

; Test f64 with round.tonearestaway (should use libcall - not supported by hardware)
define double @nearbyint_f64_tonearestaway(double %d) strictfp nounwind {
; P8-LABEL: nearbyint_f64_tonearestaway:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    stdu r1, -112(r1)
; P8-NEXT:    li r4, 4
; P8-NEXT:    std r0, 128(r1)
; P8-NEXT:    bl nearbyint
; P8-NEXT:    nop
; P8-NEXT:    addi r1, r1, 112
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f64_tonearestaway:
; P9:       # %bb.0:
; P9-NEXT:    mflr r0
; P9-NEXT:    stdu r1, -32(r1)
; P9-NEXT:    li r4, 4
; P9-NEXT:    std r0, 48(r1)
; P9-NEXT:    bl nearbyint
; P9-NEXT:    nop
; P9-NEXT:    addi r1, r1, 32
; P9-NEXT:    ld r0, 16(r1)
; P9-NEXT:    mtlr r0
; P9-NEXT:    blr
  %res = call double @llvm.experimental.constrained.nearbyint.f64(
                      double %d,
                      metadata !"round.tonearestaway",
                      metadata !"fpexcept.strict")
  ret double %res
}

; Test f32 with round.dynamic (should use libcall)
define float @nearbyint_f32_dynamic(float %f) strictfp nounwind {
; P8-LABEL: nearbyint_f32_dynamic:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    stdu r1, -112(r1)
; P8-NEXT:    li r4, 7
; P8-NEXT:    std r0, 128(r1)
; P8-NEXT:    bl nearbyintf
; P8-NEXT:    nop
; P8-NEXT:    addi r1, r1, 112
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f32_dynamic:
; P9:       # %bb.0:
; P9-NEXT:    mflr r0
; P9-NEXT:    stdu r1, -32(r1)
; P9-NEXT:    li r4, 7
; P9-NEXT:    std r0, 48(r1)
; P9-NEXT:    bl nearbyintf
; P9-NEXT:    nop
; P9-NEXT:    addi r1, r1, 32
; P9-NEXT:    ld r0, 16(r1)
; P9-NEXT:    mtlr r0
; P9-NEXT:    blr
  %res = call float @llvm.experimental.constrained.nearbyint.f32(
                      float %f,
                      metadata !"round.dynamic",
                      metadata !"fpexcept.strict")
  ret float %res
}

; Test f64 with round.dynamic (should use libcall)
define double @nearbyint_f64_dynamic(double %d) strictfp nounwind {
; P8-LABEL: nearbyint_f64_dynamic:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    stdu r1, -112(r1)
; P8-NEXT:    li r4, 7
; P8-NEXT:    std r0, 128(r1)
; P8-NEXT:    bl nearbyint
; P8-NEXT:    nop
; P8-NEXT:    addi r1, r1, 112
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f64_dynamic:
; P9:       # %bb.0:
; P9-NEXT:    mflr r0
; P9-NEXT:    stdu r1, -32(r1)
; P9-NEXT:    li r4, 7
; P9-NEXT:    std r0, 48(r1)
; P9-NEXT:    bl nearbyint
; P9-NEXT:    nop
; P9-NEXT:    addi r1, r1, 32
; P9-NEXT:    ld r0, 16(r1)
; P9-NEXT:    mtlr r0
; P9-NEXT:    blr
  %res = call double @llvm.experimental.constrained.nearbyint.f64(
                      double %d,
                      metadata !"round.dynamic",
                      metadata !"fpexcept.strict")
  ret double %res
}

; Test fp128 with round.towardzero (should use libcall - f128 always uses libcall)
define fp128 @nearbyint_f128_towardzero(fp128 %q) strictfp nounwind {
; P8-LABEL: nearbyint_f128_towardzero:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    stdu r1, -112(r1)
; P8-NEXT:    li r5, 0
; P8-NEXT:    std r0, 128(r1)
; P8-NEXT:    bl nearbyintf128
; P8-NEXT:    nop
; P8-NEXT:    addi r1, r1, 112
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f128_towardzero:
; P9:       # %bb.0:
; P9-NEXT:    xsrqpi 1, v2, v2, 1
; P9-NEXT:    blr
  %res = call fp128 @llvm.experimental.constrained.nearbyint.f128(
                      fp128 %q,
                      metadata !"round.towardzero",
                      metadata !"fpexcept.strict")
  ret fp128 %res
}

; Test fp128 with round.dynamic (should use libcall)
define fp128 @nearbyint_f128_dynamic(fp128 %q) strictfp nounwind {
; P8-LABEL: nearbyint_f128_dynamic:
; P8:       # %bb.0:
; P8-NEXT:    mflr r0
; P8-NEXT:    stdu r1, -112(r1)
; P8-NEXT:    li r5, 7
; P8-NEXT:    std r0, 128(r1)
; P8-NEXT:    bl nearbyintf128
; P8-NEXT:    nop
; P8-NEXT:    addi r1, r1, 112
; P8-NEXT:    ld r0, 16(r1)
; P8-NEXT:    mtlr r0
; P8-NEXT:    blr
;
; P9-LABEL: nearbyint_f128_dynamic:
; P9:       # %bb.0:
; P9-NEXT:    mflr r0
; P9-NEXT:    stdu r1, -32(r1)
; P9-NEXT:    li r5, 7
; P9-NEXT:    std r0, 48(r1)
; P9-NEXT:    bl nearbyintf128
; P9-NEXT:    nop
; P9-NEXT:    addi r1, r1, 32
; P9-NEXT:    ld r0, 16(r1)
; P9-NEXT:    mtlr r0
; P9-NEXT:    blr
  %res = call fp128 @llvm.experimental.constrained.nearbyint.f128(
                      fp128 %q,
                      metadata !"round.dynamic",
                      metadata !"fpexcept.strict")
  ret fp128 %res
}
