; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple powerpc64-ibm-aix-xcoff -verify-machineinstrs -mcpu=pwr7 -ppc-asm-full-reg-names  -ppc-vsr-nums-as-vr  < %s | FileCheck %s

@x2 = local_unnamed_addr global double 1.510000e+00, align 8
@val2 = local_unnamed_addr global double 0.000000e+00, align 8
@.str = private unnamed_addr constant [48 x i8] c"FAILED: nearbyintl %LF = %LF raised FE_INEXACT\0A\00", align 1
@str = private unnamed_addr constant [71 x i8] c"PASSED: nearbyintl() did not raise an inexact floating point exception\00", align 1

; Function Attrs: mustprogress norecurse nounwind strictfp
define noundef range(i32 0, 2) i32 @main() local_unnamed_addr #0 {
; CHECK-LABEL: main:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mflr r0
; CHECK-NEXT:    stdu r1, -144(r1)
; CHECK-NEXT:    lis r3, 512
; CHECK-NEXT:    std r0, 160(r1)
; CHECK-NEXT:    std r30, 128(r1) # 8-byte Folded Spill
; CHECK-NEXT:    std r31, 136(r1) # 8-byte Folded Spill
; CHECK-NEXT:    bl .feclearexcept[PR]
; CHECK-NEXT:    nop
; CHECK-NEXT:    ld r31, L..C0(r2) # @x2
; CHECK-NEXT:    lfd f1, 0(r31)
; CHECK-NEXT:    bl .nearbyint[PR]
; CHECK-NEXT:    nop
; CHECK-NEXT:    ld r30, L..C1(r2) # @val2
; CHECK-NEXT:    lis r3, 512
; CHECK-NEXT:    stfd f1, 0(r30)
; CHECK-NEXT:    bl .fetestexcept[PR]
; CHECK-NEXT:    nop
; CHECK-NEXT:    cmplwi r3, 0
; CHECK-NEXT:    beq cr0, L..BB0_2
; CHECK-NEXT:  # %bb.1: # %if.then
; CHECK-NEXT:    lfd f1, 0(r31)
; CHECK-NEXT:    ld r3, L..C2(r2) # @_MergedGlobals
; CHECK-NEXT:    stfd f1, 112(r1)
; CHECK-NEXT:    lfd f2, 0(r30)
; CHECK-NEXT:    ld r4, 112(r1)
; CHECK-NEXT:    stfd f2, 120(r1)
; CHECK-NEXT:    ld r5, 120(r1)
; CHECK-NEXT:    bl .printf[PR]
; CHECK-NEXT:    nop
; CHECK-NEXT:    li r3, 1
; CHECK-NEXT:    b L..BB0_3
; CHECK-NEXT:  L..BB0_2: # %if.else
; CHECK-NEXT:    ld r3, L..C2(r2) # @_MergedGlobals
; CHECK-NEXT:    addi r3, r3, 48
; CHECK-NEXT:    bl .puts[PR]
; CHECK-NEXT:    nop
; CHECK-NEXT:    li r3, 0
; CHECK-NEXT:  L..BB0_3: # %return
; CHECK-NEXT:    ld r31, 136(r1) # 8-byte Folded Reload
; CHECK-NEXT:    ld r30, 128(r1) # 8-byte Folded Reload
; CHECK-NEXT:    addi r1, r1, 144
; CHECK-NEXT:    ld r0, 16(r1)
; CHECK-NEXT:    mtlr r0
; CHECK-NEXT:    blr
entry:
  %call = tail call i32 @feclearexcept(i32 noundef 33554432) #5
  %0 = load double, ptr @x2, align 8, !tbaa !7
  %.strict = tail call double @llvm.experimental.constrained.nearbyint.f64(double %0, metadata !"round.tonearest", metadata !"fpexcept.ignore") #6
  store double %.strict, ptr @val2, align 8, !tbaa !7
  %call2 = tail call i32 @fetestexcept(i32 noundef 33554432) #5
  %tobool.not = icmp eq i32 %call2, 0
  br i1 %tobool.not, label %if.else, label %if.then

if.then:                                          ; preds = %entry
  %1 = load double, ptr @x2, align 8, !tbaa !7
  %2 = load double, ptr @val2, align 8, !tbaa !7
  %call3 = tail call i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str, double noundef %1, double noundef %2) #6
  br label %return

if.else:                                          ; preds = %entry
  %puts = tail call i32 @puts(ptr nonnull dereferenceable(1) @str)
  br label %return

return:                                           ; preds = %if.else, %if.then
  %retval.0 = phi i32 [ 1, %if.then ], [ 0, %if.else ]
  ret i32 %retval.0
}

; Function Attrs: nounwind
declare i32 @feclearexcept(i32 noundef) local_unnamed_addr #1

; Function Attrs: nounwind
declare i32 @fetestexcept(i32 noundef) local_unnamed_addr #1

; Function Attrs: nofree nounwind
declare noundef i32 @printf(ptr noundef readonly captures(none), ...) local_unnamed_addr #2

; Function Attrs: nofree nounwind
declare noundef i32 @puts(ptr noundef readonly captures(none)) local_unnamed_addr #3

; Function Attrs: nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite)
declare double @llvm.experimental.constrained.nearbyint.f64(double, metadata, metadata) #4

attributes #0 = { mustprogress norecurse nounwind strictfp "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="pwr7" "target-features"="+64bit,+allow-unaligned-fp-access,+altivec,+bpermd,+cmpb,+extdiv,+fcpsgn,+fpcvt,+fprnd,+fpu,+fre,+fres,+frsqrte,+frsqrtes,+fsqrt,+hard-float,+isa-v206-instructions,+isel,+ldbrx,+lfiwax,+mfocrf,+popcntd,+recipprec,+stfiwx,+two-const-nr,+vsx" }
attributes #1 = { nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="pwr7" "target-features"="+64bit,+allow-unaligned-fp-access,+altivec,+bpermd,+cmpb,+extdiv,+fcpsgn,+fpcvt,+fprnd,+fpu,+fre,+fres,+frsqrte,+frsqrtes,+fsqrt,+hard-float,+isa-v206-instructions,+isel,+ldbrx,+lfiwax,+mfocrf,+popcntd,+recipprec,+stfiwx,+two-const-nr,+vsx" }
attributes #2 = { nofree nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="pwr7" "target-features"="+64bit,+allow-unaligned-fp-access,+altivec,+bpermd,+cmpb,+extdiv,+fcpsgn,+fpcvt,+fprnd,+fpu,+fre,+fres,+frsqrte,+frsqrtes,+fsqrt,+hard-float,+isa-v206-instructions,+isel,+ldbrx,+lfiwax,+mfocrf,+popcntd,+recipprec,+stfiwx,+two-const-nr,+vsx" }
attributes #3 = { nofree nounwind }
attributes #4 = { nocallback nofree nosync nounwind strictfp willreturn memory(inaccessiblemem: readwrite) }
attributes #5 = { nounwind strictfp }
attributes #6 = { strictfp }

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}
!llvm.errno.tbaa = !{!3}

!0 = !{i32 1, !"wchar_size", i32 2}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{!"clang version 22.0.0git"}
!3 = !{!4, !4, i64 0}
!4 = !{!"int", !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!7 = !{!8, !8, i64 0}
!8 = !{!"long double", !5, i64 0}
